# Generated by Django 5.2.3 on 2025-08-09 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_phone'),
        ('disease_monitor', '0013_hospital_hospital_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital this admin manages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='disease_monitor.hospital'),
        ),
    ]
