# Generated by Django 5.2.3 on 2025-06-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CholeraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodname', models.CharField(max_length=100)),
                ('cholera_female', models.IntegerField(db_column='Cholera - Female', null=True)),
                ('cholera_male', models.IntegerField(db_column='Cholera - Male', null=True)),
                ('cholera_deaths_cds', models.IntegerField(db_column='Cholera Deaths (CDS)', null=True)),
                ('cholera_cases_cds', models.IntegerField(db_column='Cholera cases (CDS)', null=True)),
                ('cholera_cases_weekly', models.IntegerField(db_column='Cholera cases (weekly)', null=True)),
                ('cholera_deaths_weekly', models.IntegerField(db_column='Cholera deaths (weekly)', null=True)),
                ('cholera_lab_confirmed', models.IntegerField(db_column='Cholera lab confirmed cases', null=True)),
                ('cholera_lab_confirmed_weekly', models.IntegerField(db_column='Cholera lab confirmed cases (weekly)', null=True)),
                ('cholera_waho_cases', models.IntegerField(db_column='WAHO/OOAS Cholera cases', null=True)),
            ],
            options={
                'verbose_name': 'Cholera Data',
                'verbose_name_plural': 'Cholera Data',
                'db_table': 'cholera',
                'ordering': ['-periodname'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiabetesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodname', models.CharField(max_length=100)),
                ('diabetes_mellitus', models.IntegerField(db_column='Diabetes Mellitus')),
                ('diabetes_mellitus_female', models.IntegerField(db_column='Diabetes Mellitus +AC0- Female')),
                ('diabetes_mellitus_male', models.IntegerField(db_column='Diabetes Mellitus +AC0- Male')),
                ('diabetes_mellitus_deaths', models.IntegerField(db_column='Diabetes mellitus deaths')),
                ('diabetes_mellitus_lab_confirmed_cases', models.IntegerField(db_column='Diabetes mellitus lab confirmed cases')),
            ],
            options={
                'verbose_name': 'Diabetes Data',
                'verbose_name_plural': 'Diabetes Data',
                'db_table': 'diabetes',
                'ordering': ['-periodname'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeningitisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodname', models.CharField(max_length=100)),
                ('meningitis_cases', models.IntegerField(db_column='Meningitis')),
                ('meningitis_cases_female', models.IntegerField(db_column='Meningitis - Female')),
                ('meningitis_cases_male', models.IntegerField(db_column='Meningitis - Male')),
                ('meningitis_case_fatality_rate', models.IntegerField(db_column='Meningitis case fatality rate')),
                ('meningococcal_meningitis_cases_weekly', models.IntegerField(db_column='Meningococcal Meningitis cases (weekly)')),
                ('meningococcal_meningitis_deaths_weekly', models.IntegerField(db_column='Meningococcal Meningitis deaths (weekly)')),
                ('meningococcal_meningitis_lab_confirmed_cases', models.IntegerField(db_column='Meningococcal Meningitis lab confirmed cases')),
                ('meningococcal_meningitis_lab_confirmed_cases_weekly', models.IntegerField(db_column='Meningococcal Meningitis lab confirmed cases (weekly)')),
                ('meningococcal_meningitis_cases_cds', models.IntegerField(db_column='Meningococcal meningitis cases (CDS)')),
                ('meningococcal_meningitis_deaths', models.IntegerField(db_column='Meningococcal meningitis deaths')),
            ],
            options={
                'verbose_name': 'Meningitis Data',
                'verbose_name_plural': 'Meningitis Data',
                'db_table': 'meningitis',
                'ordering': ['-periodname'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodname', models.CharField(max_length=100)),
                ('hot_spots', models.CharField(max_length=3)),
                ('summary_data', models.CharField(max_length=3)),
                ('case_count_summary', models.CharField(max_length=3)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_monitor.disease')),
            ],
            options={
                'verbose_name': 'Disease Year',
                'verbose_name_plural': 'Disease Years',
                'ordering': ['-periodname'],
            },
        ),
    ]
