# Generated by Django 5.2.3 on 2025-06-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodname', models.CharField(max_length=100)),
                ('diabetes_mellitus', models.IntegerField(db_column='Diabetes Mellitus')),
                ('diabetes_mellitus_female', models.IntegerField(db_column='Diabetes Mellitus +AC0- Female')),
                ('diabetes_mellitus_male', models.IntegerField(db_column='Diabetes Mellitus +AC0- Male')),
                ('diabetes_mellitus_deaths', models.IntegerField(db_column='Diabetes mellitus deaths')),
                ('diabetes_mellitus_lab_confirmed_cases', models.IntegerField(db_column='Diabetes mellitus lab confirmed cases')),
            ],
            options={
                'verbose_name': 'Diabetes Data',
                'verbose_name_plural': 'Diabetes Data',
                'db_table': 'diabetes',
                'ordering': ['-periodname'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodname', models.CharField(max_length=100)),
                ('hot_spots', models.CharField(max_length=3)),
                ('summary_data', models.CharField(max_length=3)),
                ('case_count_summary', models.CharField(max_length=3)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_monitor.disease')),
            ],
            options={
                'verbose_name': 'Disease Year',
                'verbose_name_plural': 'Disease Years',
                'ordering': ['-periodname'],
            },
        ),
    ]
