# Generated by Django 5.2.3 on 2025-06-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CholeraData',
        ),
    ]
