# Generated by Django 5.2.3 on 2025-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalHotspots',
            fields=[
                ('organisationunitname', models.CharField(db_column='organisationunitname', max_length=100, primary_key=True, serialize=False)),
                ('cholera_lab_confirmed_cases_2020', models.IntegerField(db_column='Cholera lab confirmed cases 2020', null=True)),
                ('cholera_lab_confirmed_cases_2021', models.IntegerField(db_column='Cholera lab confirmed cases 2021', null=True)),
                ('cholera_lab_confirmed_cases_2022', models.IntegerField(db_column='Cholera lab confirmed cases 2022', null=True)),
                ('cholera_lab_confirmed_cases_2023', models.IntegerField(db_column='Cholera lab confirmed cases 2023', null=True)),
                ('cholera_lab_confirmed_cases_2024', models.IntegerField(db_column='Cholera lab confirmed cases 2024', null=True)),
                ('cholera_lab_confirmed_cases_2025', models.IntegerField(db_column='Cholera lab confirmed cases 2025', null=True)),
                ('diabetes_mellitus_lab_confirmed_cases_2020', models.IntegerField(db_column='Diabetes mellitus lab confirmed cases 2020', null=True)),
                ('diabetes_mellitus_lab_confirmed_cases_2021', models.IntegerField(db_column='Diabetes mellitus lab confirmed cases 2021', null=True)),
                ('diabetes_mellitus_lab_confirmed_cases_2022', models.IntegerField(db_column='Diabetes mellitus lab confirmed cases 2022', null=True)),
                ('diabetes_mellitus_lab_confirmed_cases_2023', models.IntegerField(db_column='Diabetes mellitus lab confirmed cases 2023', null=True)),
                ('diabetes_mellitus_lab_confirmed_cases_2024', models.IntegerField(db_column='Diabetes mellitus lab confirmed cases 2024', null=True)),
                ('diabetes_mellitus_lab_confirmed_cases_2025', models.IntegerField(db_column='Diabetes mellitus lab confirmed cases 2025', null=True)),
                ('meningococcal_meningitis_lab_confirmed_cases_2020', models.IntegerField(db_column='Meningococcal Meningitis lab confirmed cases 2020', null=True)),
                ('meningococcal_meningitis_lab_confirmed_cases_2021', models.IntegerField(db_column='Meningococcal Meningitis lab confirmed cases 2021', null=True)),
                ('meningococcal_meningitis_lab_confirmed_cases_2022', models.IntegerField(db_column='Meningococcal Meningitis lab confirmed cases 2022', null=True)),
                ('meningococcal_meningitis_lab_confirmed_cases_2023', models.IntegerField(db_column='Meningococcal Meningitis lab confirmed cases 2023', null=True)),
                ('meningococcal_meningitis_lab_confirmed_cases_2024', models.IntegerField(db_column='Meningococcal Meningitis lab confirmed cases 2024', null=True)),
                ('meningococcal_meningitis_lab_confirmed_cases_2025', models.IntegerField(db_column='Meningococcal Meningitis lab confirmed cases 2025', null=True)),
            ],
            options={
                'verbose_name': 'National Hotspots',
                'verbose_name_plural': 'National Hotspots',
                'db_table': 'national_hotspots',
                'managed': False,
            },
        ),
    ]
