# Generated by Django 5.2.3 on 2025-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0002_delete_choleradata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CholeraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodname', models.CharField(max_length=100)),
                ('cholera_female', models.IntegerField(db_column='Cholera - Female', null=True)),
                ('cholera_male', models.IntegerField(db_column='Cholera - Male', null=True)),
                ('cholera_deaths_cds', models.IntegerField(db_column='Cholera Deaths (CDS)', null=True)),
                ('cholera_cases_cds', models.IntegerField(db_column='Cholera cases (CDS)', null=True)),
                ('cholera_cases_weekly', models.IntegerField(db_column='Cholera cases (weekly)', null=True)),
                ('cholera_deaths_weekly', models.IntegerField(db_column='Cholera deaths (weekly)', null=True)),
                ('cholera_lab_confirmed', models.IntegerField(db_column='Cholera lab confirmed cases', null=True)),
                ('cholera_lab_confirmed_weekly', models.IntegerField(db_column='Cholera lab confirmed cases (weekly)', null=True)),
                ('cholera_waho_cases', models.IntegerField(db_column='WAHO/OOAS Cholera cases', null=True)),
            ],
            options={
                'verbose_name': 'Cholera Data',
                'verbose_name_plural': 'Cholera Data',
                'db_table': 'cholera',
                'ordering': ['-periodname'],
                'managed': False,
            },
        ),
    ]
