# Generated by Django 5.2.3 on 2025-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0002_nationalhotspots'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('periodname', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Region Population',
                'verbose_name_plural': 'Region Populations',
                'db_table': 'region_population',
                'ordering': ['-periodname', 'region'],
                'unique_together': {('region', 'periodname')},
            },
        ),
    ]
