# Generated by Django 5.2.3 on 2025-07-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0003_regionpopulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('trend_value', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='disease_monitor.disease')),
            ],
            options={
                'verbose_name': 'Disease Trend',
                'verbose_name_plural': 'Disease Trends',
                'ordering': ['disease', 'year', 'month'],
                'unique_together': {('disease', 'year', 'month')},
            },
        ),
    ]
