# Generated by Django 5.2.3 on 2025-07-17 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0004_diseasetrends'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalHealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=100)),
                ('address_locality', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('principal_diagnosis_new', models.CharField(max_length=255)),
                ('additional_diagnosis_new', models.CharField(blank=True, max_length=255, null=True)),
                ('pregnant_patient', models.BooleanField()),
                ('nhia_patient', models.BooleanField()),
                ('month', models.DateField()),
            ],
            options={
                'verbose_name': 'Hospital Health Data',
                'verbose_name_plural': 'Hospital Health Data',
                'indexes': [models.Index(fields=['orgname', 'month'], name='disease_mon_orgname_477062_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommonSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_symptoms', to='disease_monitor.disease')),
            ],
            options={
                'ordering': ['disease', 'rank'],
                'unique_together': {('disease', 'symptom')},
            },
        ),
    ]
