# Generated by Django 5.2.3 on 2025-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0005_hospitalhealthdata_commonsymptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonsymptom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
