# Generated by Django 5.2.3 on 2025-07-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0006_commonsymptom_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=100)),
                ('address_locality', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('pregnant_patient', models.BooleanField()),
                ('nhia_patient', models.BooleanField()),
                ('disease_type', models.CharField(max_length=50)),
                ('symptoms', models.TextField()),
                ('prediction', models.CharField(max_length=100)),
                ('probability', models.FloatField()),
                ('gemini_enabled', models.BooleanField(default=False)),
                ('gemini_recommendation', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
