# Generated by Django 5.2.3 on 2025-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0007_predictionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalLocalities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('locality', models.CharField(help_text="Patient's residential area", max_length=255)),
                ('orgname', models.CharField(help_text='Healthcare facility name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Locality',
                'verbose_name_plural': 'Hospital Localities',
                'db_table': 'hospital_localities',
                'ordering': ['locality', 'orgname'],
                'indexes': [models.Index(fields=['locality'], name='hospital_lo_localit_b7788e_idx'), models.Index(fields=['orgname'], name='hospital_lo_orgname_8a3858_idx'), models.Index(fields=['locality', 'orgname'], name='hospital_lo_localit_bbc2d2_idx')],
                'unique_together': {('locality', 'orgname')},
            },
        ),
    ]
