# Generated by Django 5.2.3 on 2025-07-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0008_hospitallocalities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Hospital name', max_length=255, unique=True)),
                ('slug', models.CharField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospitals',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='hospitals_name_9e93ed_idx'), models.Index(fields=['slug'], name='hospitals_slug_26fb1e_idx')],
            },
        ),
    ]
