# Generated by Django 5.2.3 on 2025-08-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0009_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalhealthdata',
            name='cost_of_treatment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hospitalhealthdata',
            name='data_source',
            field=models.CharField(blank=True, default='legacy', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitalhealthdata',
            name='locality_encoded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalhealthdata',
            name='medicine_prescribed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalhealthdata',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
