# Generated by Django 5.2.3 on 2025-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0011_predictionhistory_predictionfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='ai_insights',
            field=models.JSONField(blank=True, help_text='AI-generated insights for this prediction', null=True),
        ),
    ]
