# Generated by Django 5.2.3 on 2025-08-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0012_predictionhistory_ai_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='System-generated unique hospital identifier', max_length=16, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['hospital_id'], name='hospitals_hospita_8adbbd_idx'),
        ),
    ]
