# Generated by Django 5.2.3 on 2025-08-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_monitor', '0013_hospital_hospital_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleTrendsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(help_text='Unique cache key for this request', max_length=255, unique=True)),
                ('disease_name', models.CharField(help_text='Disease name (diabetes, malaria, meningitis, cholera)', max_length=100)),
                ('data_type', models.CharField(help_text='Type of data (interest_over_time, related_queries, related_topics, etc.)', max_length=50)),
                ('timeframe', models.CharField(help_text="Timeframe for the data (e.g., 'today 12-m', '2020-01-01 2025-12-31')", max_length=50)),
                ('geo', models.CharField(blank=True, help_text="Geographic location (e.g., 'GH' for Ghana)", max_length=10, null=True)),
                ('cached_data', models.JSONField(help_text='The actual cached Google Trends data')),
                ('last_fetched', models.DateTimeField(auto_now_add=True, help_text='When this data was last fetched from Google')),
                ('cache_expiry', models.DateTimeField(help_text='When this cache expires')),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('stale', 'Stale'), ('expired', 'Expired')], default='fresh', max_length=20)),
                ('fetch_count', models.IntegerField(default=0, help_text='Number of times this data has been fetched from Google')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time this cache was accessed')),
                ('last_error', models.TextField(blank=True, help_text='Last error encountered when fetching', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
            ],
            options={
                'verbose_name': 'Google Trends Cache',
                'verbose_name_plural': 'Google Trends Cache',
                'db_table': 'google_trends_cache',
                'ordering': ['-last_fetched'],
                'indexes': [models.Index(fields=['disease_name', 'data_type'], name='google_tren_disease_33a6a2_idx'), models.Index(fields=['cache_key'], name='google_tren_cache_k_f3a931_idx'), models.Index(fields=['status', 'cache_expiry'], name='google_tren_status_883872_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(help_text='Disease name', max_length=100)),
                ('date', models.DateField(help_text='Date of the metrics')),
                ('search_interest', models.FloatField(help_text='Average search interest score (0-100)')),
                ('peak_interest', models.FloatField(help_text='Peak search interest for the day')),
                ('total_searches', models.BigIntegerField(help_text='Estimated total searches (derived from interest)')),
                ('trend_direction', models.CharField(choices=[('rising', 'Rising'), ('falling', 'Falling'), ('stable', 'Stable'), ('volatile', 'Volatile')], help_text='Overall trend direction', max_length=20)),
                ('trend_strength', models.FloatField(help_text='Strength of the trend (-1 to 1)')),
                ('top_related_queries', models.JSONField(default=list, help_text='Top related search queries')),
                ('top_related_topics', models.JSONField(default=list, help_text='Top related topics')),
                ('top_regions', models.JSONField(default=list, help_text='Top regions by search interest')),
                ('regional_distribution', models.JSONField(default=dict, help_text='Regional search distribution')),
                ('data_source', models.CharField(default='google_trends', help_text='Source of the data', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Trends Metrics',
                'verbose_name_plural': 'Google Trends Metrics',
                'db_table': 'google_trends_metrics',
                'ordering': ['-date', 'disease_name'],
                'indexes': [models.Index(fields=['disease_name', 'date'], name='google_tren_disease_db4244_idx'), models.Index(fields=['trend_direction'], name='google_tren_trend_d_686f3a_idx'), models.Index(fields=['search_interest'], name='google_tren_search__c99f1d_idx')],
                'unique_together': {('disease_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disease_name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('timeframe', models.CharField(max_length=50)),
                ('geo', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('rate_limited', 'Rate Limited'), ('error', 'Error'), ('cached', 'Served from Cache')], max_length=20)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('cache_hit', models.BooleanField(default=False, help_text='Whether data was served from cache')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('rate_limit_remaining', models.IntegerField(blank=True, help_text='Remaining requests in current window', null=True)),
                ('rate_limit_reset', models.DateTimeField(blank=True, help_text='When rate limit resets', null=True)),
            ],
            options={
                'verbose_name': 'Google Trends Request Log',
                'verbose_name_plural': 'Google Trends Request Logs',
                'db_table': 'google_trends_request_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='google_tren_timesta_4f320c_idx'), models.Index(fields=['disease_name', 'status'], name='google_tren_disease_4dce4e_idx'), models.Index(fields=['status', 'timestamp'], name='google_tren_status_ce2624_idx')],
            },
        ),
    ]
